"""
Independent Logic Grid constraint-propagation solver.

Given:
  - people: list of primary-category items (the "rows" of the grid)
  - items_by_cat: {category: [item, ...]}
  - other_cats: list of non-primary category names
  - clues: list of English clue strings

The solver maintains a possibility matrix:
  possible[person][cat] = set of items that could still be assigned

It repeatedly applies clues until no more progress is possible, then checks
whether the assignment is unique.

Supported clue formats (generated by LogicGridGenerator):
  "X has the Y."                        → positive: person X → cat containing Y = Y
  "X does NOT have the Y."              → negative: eliminate Y from X's category
  "The person with the Y also has Z."   → cross-category link
"""
from __future__ import annotations

import copy
import re
from typing import Optional


class LogicSolver:
    """Constraint-propagation solver for logic grid puzzles."""

    def __init__(
        self,
        people: list[str],
        items_by_cat: dict[str, list[str]],
        other_cats: list[str],
        clues: list[str],
    ) -> None:
        self.people = people
        self.items_by_cat = items_by_cat
        self.other_cats = other_cats
        self.clues = clues

        # possible[person][cat] = set of candidate items
        self.possible: dict[str, dict[str, set[str]]] = {
            person: {
                cat: set(items_by_cat[cat])
                for cat in other_cats
            }
            for person in people
        }

    def solve(self) -> Optional[dict[str, dict[str, str]]]:
        """
        Run constraint propagation and backtracking to find all solutions.
        Returns the unique solution dict {person: {cat: item}} if exactly one exists.
        Otherwise returns None.
        """
        solutions = self.find_all_solutions()
        if len(solutions) == 1:
            return solutions[0]
        return None

    def find_all_solutions(self) -> list[dict[str, dict[str, str]]]:
        """Find all valid solutions using propagation and backtracking."""
        return self._search(self.possible)

    def _search(self, poss: dict) -> list[dict[str, dict[str, str]]]:
        # 1. Propagate until convergence
        changed = True
        while changed:
            changed = False
            for clue in self.clues:
                if self._apply_clue(poss, clue):
                    changed = True
            if self._propagate(poss):
                changed = True
        
        # Check for contradictions
        for person in self.people:
            for cat in self.other_cats:
                if len(poss[person][cat]) == 0:
                    return [] # Contradiction

        # Check if solved
        solved = True
        min_options = float('inf')
        best_branch = None

        for person in self.people:
            for cat in self.other_cats:
                n = len(poss[person][cat])
                if n > 1:
                    solved = False
                    if n < min_options:
                        min_options = n
                        best_branch = (person, cat)

        if solved:
            return [self._extract(poss)]

        # Backtrack
        person, cat = best_branch
        solutions = []
        for item in list(poss[person][cat]):
            new_poss = copy.deepcopy(poss)
            new_poss[person][cat] = {item}
            solutions.extend(self._search(new_poss))
            if len(solutions) > 1:
                # We only care about uniqueness, so finding 2 is enough
                return solutions
                
        return solutions

    # ------------------------------------------------------------------
    # Clue application
    # ------------------------------------------------------------------

    def _apply_clue(self, poss: dict, clue: str) -> bool:
        changed = False

        # Pattern 1: "X has the Y."
        m = re.match(r"^(\w+) has the (.+)\.$", clue)
        if m:
            person, item = m.group(1), m.group(2)
            if person in self.people:
                cat = self._cat_of(item)
                if cat and item in poss.get(person, {}).get(cat, set()):
                    if len(poss[person][cat]) > 1:
                        poss[person][cat] = {item}
                        changed = True
            return changed

        # Pattern 2: "X does NOT have the Y."
        m = re.match(r"^(\w+) does NOT have the (.+)\.$", clue)
        if m:
            person, item = m.group(1), m.group(2)
            if person in self.people:
                cat = self._cat_of(item)
                if cat and item in poss.get(person, {}).get(cat, set()):
                    poss[person][cat].discard(item)
                    changed = True
            return changed

        # Pattern 3: "The person with the Y also has Z."
        m = re.match(r"^The person with the (.+) also has the (.+)\.$", clue)
        if m:
            item_a, item_b = m.group(1), m.group(2)
            cat_a = self._cat_of(item_a)
            cat_b = self._cat_of(item_b)
            if cat_a and cat_b:
                for person in self.people:
                    if poss[person][cat_a] == {item_a}:
                        # This person has item_a → must have item_b
                        if item_b in poss[person][cat_b] and len(poss[person][cat_b]) > 1:
                            poss[person][cat_b] = {item_b}
                            changed = True
                    elif item_a not in poss[person][cat_a]:
                        # This person definitely does NOT have item_a → no constraint on item_b
                        pass
                    # If person does NOT have item_b, they can't have item_a
                    if item_b not in poss[person][cat_b]:
                        if item_a in poss[person][cat_a]:
                            poss[person][cat_a].discard(item_a)
                            changed = True

        return changed

    def _propagate(self, poss: dict) -> bool:
        """
        If a person has only one possibility for a category, eliminate that item
        from all other people's possibilities for that category.
        """
        changed = False
        for person in self.people:
            for cat in self.other_cats:
                candidates = poss[person][cat]
                if len(candidates) == 1:
                    forced_item = next(iter(candidates))
                    for other in self.people:
                        if other != person and forced_item in poss[other][cat]:
                            poss[other][cat].discard(forced_item)
                            changed = True
        return changed

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _cat_of(self, item: str) -> Optional[str]:
        """Find which other_cat an item belongs to."""
        for cat in self.other_cats:
            if item in self.items_by_cat[cat]:
                return cat
        return None

    def _extract(self, poss: dict) -> dict[str, dict[str, str]]:
        result: dict[str, dict[str, str]] = {}
        for person in self.people:
            result[person] = {}
            for cat in self.other_cats:
                result[person][cat] = next(iter(poss[person][cat]))
        return result
